version: 2
jobs:
   build:
     docker:
       - image: circleci/python:2-stretch-node-browsers
       - image: circleci/ruby:rc-node-browsers
     steps:
       - checkout
       - run: echo "hello world"
       - run: echo "hello world"