version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:
          name: Build images
          command: docker-compose build
     - run:
          name: Run tests
          command: docker-compose -f docker-compose.test.yml run --rm api