# circle.yml
machine:
  pre:
    - sudo curl -L -o /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m`
    - sudo chmod +x /usr/local/bin/docker-compose
  services:
    - docker

dependencies:
  pre:
    - docker-compose build

test:
  post:
    - docker-compose exec api python manage.py test