version: 2
jobs:
  build:
    working_directory: ~/polls
    docker:
      - image: haskell:8.2.1
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get install python3-pip
            pip install docker-compose
            docker-compose build